[workspace]
members = [
    "proto-hal",
    "proto-ral"
]
exclude = [
    "examples/delay",
    "examples/teensy4"
]

[patch.crates-io.imxrt-iomuxc]
rev = "14aa29e"
git = "https://github.com/imxrt-rs/imxrt-rs"